from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors as rl_colors
from datetime import datetime
import os

def _hex_to_rl(hex_color: str):
    hex_color = hex_color.lstrip("#")
    r = int(hex_color[0:2], 16) / 255.0
    g = int(hex_color[2:4], 16) / 255.0
    b = int(hex_color[4:6], 16) / 255.0
    return rl_colors.Color(r, g, b)

def generate_report(pdf_path: str, report_id: str, a: dict):
    os.makedirs(os.path.dirname(pdf_path), exist_ok=True)

    c = canvas.Canvas(pdf_path, pagesize=A4)
    W, H = A4
    y = H - 40

    risk_color = _hex_to_rl(a["risk_color_hex"])

    def hr():
        nonlocal y
        c.setStrokeColor(rl_colors.lightgrey)
        c.setLineWidth(1)
        c.line(40, y, W - 40, y)
        y -= 16

    def text(s, size=10, gap=14, bold=False):
        nonlocal y
        c.setFillColor(rl_colors.black)
        c.setFont("Helvetica-Bold" if bold else "Helvetica", size)
        c.drawString(40, y, s)
        y -= gap

    def pill(label):
        nonlocal y
        # Colored badge
        c.setFillColor(risk_color)
        c.roundRect(40, y - 6, 260, 18, 8, fill=1, stroke=0)
        c.setFillColor(rl_colors.white)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(50, y, label)
        y -= 22

    # Top color strip
    c.setFillColor(risk_color)
    c.rect(0, H - 12, W, 12, fill=1, stroke=0)

    # Header
    text("PinIT Image Forensics & Risk Assessment Report", 14, 20, True)
    text("Prepared for: Insurance Claims & Fraud Investigation Team")
    text("Generated by: PinIT – Digital Intelligence Platform")
    text("Report Type: Digital Image Authenticity & Risk Analysis")
    text(f"Report ID: {report_id}")
    text(f"Date: {datetime.now().strftime('%d %b %Y')}")
    hr()

    # 1 Executive Summary
    text("1. Executive Summary", 12, 18, True)
    text("PinIT analyzed the submitted claim image using image forensics, metadata intelligence, and tamper analysis.")
    pill(f"{a['risk_label']}  |  Authenticity Score: {a['authenticity_score']} / 100")
    text("Summary:", bold=True)
    if a["risk_label"] in ("Highly Authentic", "Low Risk"):
        text("Image appears consistent with expected capture patterns; no strong manipulation indicators found.")
    elif a["risk_label"] == "Medium Risk":
        text("Some inconsistencies detected across metadata and/or localized compression patterns; manual review recommended.")
    else:
        text("High likelihood of manipulation or post-processing; escalate for enhanced fraud review.")
    hr()

    # 2 Image Overview
    text("2. Image Overview", 12, 18, True)
    text("Capture Method: PinIT Secure Capture App" if a["uuid_embedded"] else "Capture Method: Unknown / Standard Upload")
    text(f"User UUID Embedded: {a['uuid_hint']}")
    text(f"Capture Integrity Status: {a['chain_of_custody_status']}")
    text(f"• Image Type: JPEG/PNG (Detected)")
    text(f"• File Size: {a['file_size_mb']} MB")
    text(f"• Resolution: {a['width']} × {a['height']} pixels")
    text(f"• Color Space: {a['color_space']}")
    hr()

    # 3 Authenticity Score
    text("3. Image Authenticity Score", 12, 18, True)
    text(f"Authenticity Confidence Score: {a['authenticity_score']} / 100", bold=True)
    text("Score Range  |  Interpretation")
    text("80–100       |  Highly Authentic")
    text("60–79        |  Partially Authentic / Medium Risk")
    text("40–59        |  Suspicious")
    text("Below 40     |  High Fraud Risk")
    text(f"PinIT Verdict: {a['risk_label']}.")
    hr()

    # 4 Chain of Custody
    text("4. Capture Encryption & Chain of Custody", 12, 18, True)
    text("PinIT Secure Capture ensures cryptographic integrity at the moment of image creation.")
    text(f"Chain of Custody Status: {a['chain_of_custody_status']}", bold=True)
    hr()

    # 5 Metadata
    text("5. Metadata Analysis Report", 12, 18, True)
    text(f"EXIF Present: {a['exif_present']}")
    text(f"Software Tag: {a['software_tag']}")
    text(f"Date & Time (EXIF): {a['datetime_original']}")
    text(f"GPS Data Present: {a['gps_present']}")
    text(f"Metadata Integrity Score: {a['metadata_integrity_score']} / 100", bold=True)
    hr()

    # 6 Tampering
    text("6. Tampering & Manipulation Analysis", 12, 18, True)
    text("Methods: Error Level Analysis (ELA), compression inconsistency scoring.")
    text(f"ELA Mean: {a['ela_mean']}")
    text(f"ELA 95th Percentile: {a['ela_p95']}")
    text(f"Tampering Probability: {a['tampering_probability']}%", bold=True)
    hr()

    # 7 Duplicate & reuse (placeholder without web search)
    text("7. Duplicate & Reuse Image Check", 12, 18, True)
    text("Local similarity checks: Not implemented in this build (optional upgrade).")
    text("Recommendation: add reverse-image search API for web-scale matching.")
    hr()

    # 8 Geo & time verification (based on EXIF only in this build)
    text("8. Geo & Timestamp Verification", 12, 18, True)
    if a["gps_present"]:
        text("GPS available in EXIF: Basic geo-verification possible.")
    else:
        text("GPS missing: Geo-verification limited; consider requiring location evidence.")
    if a["datetime_original"] != "Unknown":
        text("Timestamp available: Basic timeline validation possible.")
    else:
        text("Timestamp missing: Timeline validation limited.")
    hr()

    # 9 Risk classification
    text("9. Risk Classification", 12, 18, True)
    text("Risk Factor Scores (derived):")
    bd = a["score_breakdown"]
    text(f"• Metadata penalties: {bd['metadata_penalty']}")
    text(f"• Tampering penalties: {bd['tamper_penalty']}")
    text(f"• AI-like anomaly penalties: {bd['ai_penalty']}")
    text(f"• Secure capture bonus: {bd['secure_bonus']}")
    text(f"Overall Risk Rating: {a['risk_label']}", bold=True)
    hr()

    # 10 Visual (color legend)
    text("10. Visual Risk Legend", 12, 18, True)
    text("Blue (#1F4FFF): Highly Authentic")
    text("Green (#1FAF55): Low Risk")
    text("Amber (#FF9F1C): Medium Risk")
    text("Red (#E63946): High Fraud Risk")
    hr()

    # 11 Recommendation
    text("11. PinIT Recommendation to Insurance Team", 12, 18, True)
    if a["risk_label"] in ("Highly Authentic", "Low Risk"):
        text("✔ Proceed with standard claim validation.")
    elif a["risk_label"] == "Medium Risk":
        text("✔ Request original file and additional supporting photos/video.")
        text("✔ Manual review recommended.")
    else:
        text("✔ Escalate for enhanced fraud review.")
        text("✔ Request original file + device capture evidence.")
    hr()

    # 12 Disclaimer
    text("12. Legal & Compliance Disclaimer", 12, 18, True)
    text("This report is generated using automated analysis. Results are probability-based and should be used with human judgment.")
    text("PinIT does not make final claim approval or rejection decisions.")
    y -= 8
    text("Prepared by:", bold=True)
    text("PinIT – Protecting Trust in Digital Evidence")

    c.showPage()
    c.save()
