import os

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet


def _tbl(data, col_widths=None):
    t = Table(data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def build_pdf_report(analysis: dict, pdf_path: str, report_id: str):
    os.makedirs(os.path.dirname(pdf_path), exist_ok=True)

    styles = getSampleStyleSheet()
    H = styles["Heading2"]
    N = styles["BodyText"]

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=1.6 * cm,
        leftMargin=1.6 * cm,
        topMargin=1.6 * cm,
        bottomMargin=1.6 * cm
    )

    story = []

    # Title
    story.append(Paragraph("PinIT Image Forensics &amp; Risk Assessment Report", styles["Title"]))
    story.append(Spacer(1, 6))

    story.append(Paragraph("<b>Prepared for:</b> Insurance Claims &amp; Fraud Investigation Team", N))
    story.append(Paragraph("<b>Generated by:</b> PinIT – Digital Intelligence Platform", N))
    story.append(Paragraph("<b>Report Type:</b> Digital Image Authenticity &amp; Risk Analysis", N))
    story.append(Paragraph(f"<b>Report ID:</b> {report_id}", N))
    story.append(Paragraph(f"<b>Date:</b> {analysis.get('generated_at','')}", N))
    story.append(Spacer(1, 12))

    # 1. Executive Summary
    story.append(Paragraph("1. Executive Summary", H))
    ex = analysis["executive_summary"]
    story.append(Paragraph(f"<b>Overall Finding:</b> {ex['overall_finding']}", N))
    story.append(Paragraph(ex["finding_details"], N))
    story.append(Spacer(1, 10))

    # 2. Image Overview
    story.append(Paragraph("2. Image Overview", H))
    ov = analysis["image_overview"]
    story.append(Paragraph(f"<b>Capture Method:</b> {ov['capture_method']}", N))
    story.append(Paragraph(f"<b>User UUID Embedded:</b> {ov['user_uuid_embedded']}", N))
    story.append(Paragraph(f"<b>Capture Integrity Status:</b> {ov['capture_integrity_status']}", N))
    story.append(Spacer(1, 6))

    overview_tbl = _tbl([
        ["Field", "Value"],
        ["Image Type", ov["image_type"]],
        ["File Size", f"{ov['file_size_mb']} MB"],
        ["Resolution", ov["resolution"]],
        ["Color Space", ov["color_space"]],
        ["Compression Artifacts", ov["compression_artifacts"]],
        ["SHA-256", analysis["file_hash"]["sha256"]],
    ], col_widths=[5.2 * cm, 11.0 * cm])
    story.append(overview_tbl)
    story.append(Spacer(1, 8))

    sec_layers = "<br/>".join([f"• {x}" for x in ov.get("embedded_security_layers", [])])
    story.append(Paragraph(f"<b>Embedded Security Layers:</b><br/>{sec_layers}", N))
    story.append(Spacer(1, 10))

    # 3. Image Authenticity Score
    story.append(Paragraph("3. Image Authenticity Score", H))
    au = analysis["authenticity"]
    story.append(Paragraph(f"<b>Authenticity Confidence Score:</b> {au['score']} / 100", N))
    ranges = [["Score Range", "Interpretation"]] + [[a, b] for a, b in au["score_range_guide"]]
    story.append(Spacer(1, 6))
    story.append(_tbl(ranges, col_widths=[5.2 * cm, 11.0 * cm]))
    story.append(Spacer(1, 10))
    story.append(Paragraph(f"<b>PinIT Verdict:</b> {au['label']}", N))
    story.append(Spacer(1, 12))

    # 4. Capture Encryption & Chain of Custody
    story.append(Paragraph("4. Capture Encryption & Chain of Custody", H))
    ch = analysis["chain_of_custody"]
    coc_tbl = _tbl([
        ["Security Attribute", "Status / Details"],
        ["Capture-Time Encryption", f"{ch['capture_time_encryption']} — {ch['encryption_details']}"],
        ["User Identity Binding", ch["user_identity_binding"]],
        ["Image-Level UUID Injection", ch["image_uuid_injection"]],
        ["Post-Capture Editing", ch["post_capture_editing"]],
        ["Hash Generated at Capture", f"{ch['hash_algo']}"],
        ["Upload Transport Security", ch["transport_security"]],
        ["Server-Side Re-Encryption", ch["server_side_encryption"]],
    ], col_widths=[6.2 * cm, 10.0 * cm])
    story.append(coc_tbl)
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"<b>Chain of Custody Status:</b> {ch['chain_status']}", N))
    story.append(Spacer(1, 12))

    # 5. Metadata Analysis Report
    story.append(Paragraph("5. Metadata Analysis Report", H))
    md = analysis["metadata"]
    exif = md["exif"]

    story.append(Paragraph(f"<b>EXIF Metadata Status:</b> {md['exif_status']}", N))
    meta_tbl = _tbl([
        ["Parameter", "Extracted Value", "Observation"],
        ["Device Model", (exif.get("model") or "Unknown"), "Device model from EXIF" if exif.get("model") else "Missing"],
        ["Device Make", (exif.get("make") or "Unknown"), "Device make from EXIF" if exif.get("make") else "Missing"],
        ["Date & Time", (exif.get("datetime") or "Unknown"), "Capture timestamp" if exif.get("datetime") else "Missing"],
        ["GPS Data", "Present" if exif.get("gps_present") else "Removed / Missing", "Location data available" if exif.get("gps_present") else "Location data stripped"],
        ["Software Tag", (exif.get("software") or "None"), "Indicates post-processing" if exif.get("software") else "No editing software tag detected"],
    ], col_widths=[4.2 * cm, 6.0 * cm, 6.0 * cm])
    story.append(Spacer(1, 6))
    story.append(meta_tbl)
    story.append(Spacer(1, 6))

    obs = md.get("observations", [])
    if obs:
        story.append(Paragraph("<b>Observations:</b><br/>" + "<br/>".join([f"• {o}" for o in obs]), N))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"<b>Metadata Integrity Score:</b> {md['integrity_score']} / 100", N))
    story.append(Spacer(1, 12))

    # 6. Tampering & Manipulation Analysis
    story.append(Paragraph("6. Tampering & Manipulation Analysis", H))
    tp = analysis["tampering"]
    findings = "<br/>".join([f"• {x}" for x in tp.get("findings", [])])
    story.append(Paragraph(f"<b>Findings:</b><br/>{findings}", N))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"<b>ELA Avg:</b> {tp['ela_avg']} &nbsp;&nbsp; <b>High-Anomaly Ratio:</b> {tp['ela_high_ratio_pct']}%", N))
    story.append(Paragraph(f"<b>Tampering Probability:</b> {tp['tampering_probability_pct']}%", N))
    story.append(Spacer(1, 10))

    # 7. Deepfake & Synthetic Content Detection
    story.append(Paragraph("7. Deepfake & Synthetic Content Detection", H))
    df = analysis["deepfake"]
    story.append(Paragraph(f"<b>AI-Generated Content:</b> {df['ai_generated_content']}", N))
    story.append(Paragraph(f"<b>AI-Assisted Editing:</b> {df['ai_assisted_editing']}", N))
    story.append(Paragraph(f"<b>Deepfake Risk Score:</b> {df['risk_score']} / 100", N))
    story.append(Paragraph(f"<b>Interpretation:</b> {df['interpretation']}", N))
    if df.get("signals"):
        story.append(Spacer(1, 4))
        story.append(Paragraph("<b>Signals:</b><br/>" + "<br/>".join([f"• {s}" for s in df["signals"]]), N))
    story.append(Spacer(1, 12))

    # 8. Duplicate & Reuse Image Check
    story.append(Paragraph("8. Duplicate & Reuse Image Check", H))
    du = analysis["duplicate_reuse"]
    story.append(Paragraph(f"<b>Exact Match:</b> {du['exact_match_details']}", N))
    if du["near_duplicate_found"]:
        story.append(Paragraph(f"<b>Near-Duplicate Match:</b> ⚠️ Similar image found ({du['near_duplicate_similarity_pct']}% similarity)", N))
        story.append(Paragraph(f"<b>Details:</b> {du['near_duplicate_details']}", N))
    else:
        story.append(Paragraph("<b>Near-Duplicate Match:</b> Not Found", N))
    story.append(Paragraph(f"<b>Reuse Risk Level:</b> {du['reuse_risk_level']}", N))
    story.append(Spacer(1, 12))

    # 9. Geo & Timestamp Verification
    story.append(Paragraph("9. Geo & Timestamp Verification", H))
    gt = analysis["geo_time"]
    gt_tbl = _tbl([
        ["Parameter", "Result"],
        ["Claimed Location", gt["claimed_location"]],
        ["GPS Present", "Yes" if gt["gps_present"] else "No"],
        ["GPS Coordinates", gt["gps_coordinates"]],
    ], col_widths=[6.2 * cm, 10.0 * cm])
    story.append(gt_tbl)
    story.append(Spacer(1, 6))
    if gt.get("notes"):
        story.append(Paragraph("<b>Notes:</b><br/>" + "<br/>".join([f"• {n}" for n in gt["notes"]]), N))
        story.append(Spacer(1, 6))
    story.append(Paragraph(f"<b>Geo-Time Confidence Score:</b> {gt['confidence_score']} / 100 ({gt['confidence_level']})", N))
    story.append(Spacer(1, 12))

    # 10. Risk Classification
    story.append(Paragraph("10. Risk Classification", H))
    rc = analysis["risk_classification"]
    rf = rc["risk_factors"]
    rf_tbl = _tbl(
        [["Risk Factor", "Score"]] + [[k, str(v)] for k, v in rf.items()],
        col_widths=[9.0 * cm, 7.2 * cm]
    )
    story.append(rf_tbl)
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"<b>Overall Risk Rating:</b> {rc['overall_risk_rating']}", N))
    story.append(Paragraph(f"<b>Recommended Action:</b> {rc['recommended_action']}", N))
    story.append(Spacer(1, 12))

    # 11. Visual Manipulation Heatmap
    story.append(Paragraph("11. Visual Manipulation Heatmap", H))
    story.append(Paragraph("(Heatmap highlights regions with abnormal noise/compression differences.)", N))
    story.append(Spacer(1, 6))

    heat_path = analysis["tampering"].get("heatmap_path")
    if heat_path and os.path.exists(heat_path):
        story.append(RLImage(heat_path, width=16.5 * cm, height=9.5 * cm))
        story.append(Spacer(1, 8))
        story.append(Paragraph("Red zones: higher likelihood of manipulation • Orange: possible edits • Dark: lower anomalies", N))
    else:
        story.append(Paragraph("Heatmap not available.", N))
    story.append(Spacer(1, 12))

    # 12. Recommendation + Disclaimer
    story.append(Paragraph("12. PinIT Recommendation to Insurance Team", H))
    story.append(Paragraph("• Request original image file directly from device<br/>"
                           "• Cross-check claim with additional photos or videos<br/>"
                           "• Validate claim timeline with external evidence<br/>"
                           "• Flag claim for enhanced fraud review",
                           N))
    story.append(Spacer(1, 12))

    story.append(Paragraph("13. Legal & Compliance Disclaimer", H))
    story.append(Paragraph(
        "This report is generated using automated forensic analysis and heuristic AI checks. "
        "Results indicate probability-based assessments and should be used alongside human judgment and supporting evidence.",
        N
    ))
    story.append(Spacer(1, 10))
    story.append(Paragraph("Prepared by: PinIT – Protecting Trust in Digital Evidence", N))

    doc.build(story)
