from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from textwrap import wrap
import os
from datetime import datetime

# ==============================
# PAGE CONFIG
# ==============================
PAGE_WIDTH, PAGE_HEIGHT = A4
LEFT = 2 * cm
RIGHT = PAGE_WIDTH - 2 * cm
TOP = PAGE_HEIGHT - 2 * cm
BOTTOM = 2 * cm
LINE = 0.45 * cm


# ==============================
# HELPERS
# ==============================
def safe(v, default="N/A"):
    return default if v in (None, "", []) else v


def new_page_if_needed(c, y, needed=LINE * 3):
    if y < BOTTOM + needed:
        c.showPage()
        c.setFont("Helvetica", 10)
        return TOP
    return y


def header(c, title, y):
    y = new_page_if_needed(c, y)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(LEFT, y, title)
    return y - LINE * 1.5


def text(c, txt, y, width=95):
    c.setFont("Helvetica", 10)
    for line in wrap(str(txt), width):
        y = new_page_if_needed(c, y)
        c.drawString(LEFT, y, line)
        y -= LINE
    return y


def bullet_list(c, items, y):
    if not items:
        return text(c, "• No significant indicators detected.", y)
    for i in items:
        y = text(c, f"• {i}", y)
    return y


def divider(c, y):
    y = new_page_if_needed(c, y)
    c.line(LEFT, y, RIGHT, y)
    return y - LINE


# ==============================
# MAIN BUILDER (12 SECTIONS)
# ==============================
def build_pdf_report(analysis: dict, pdf_path: str):
    os.makedirs(os.path.dirname(pdf_path), exist_ok=True)

    c = canvas.Canvas(pdf_path, pagesize=A4)
    y = TOP

    # -------- TITLE --------
    c.setFont("Helvetica-Bold", 16)
    c.drawString(LEFT, y, "PinIT Image Forensics & Risk Assessment Report")
    y -= LINE * 2

    c.setFont("Helvetica", 10)
    y = text(c, "Prepared for: Insurance Claims & Fraud Investigation Team", y)
    y = text(c, "Generated by: PinIT – Digital Intelligence Platform", y)
    y = text(c, f"Date: {analysis.get('generated_at', datetime.utcnow().isoformat())}", y)
    y = divider(c, y)

    scores = analysis.get("scores", {})

    # -------- 1 --------
    y = header(c, "1. Executive Summary", y)
    y = text(
        c,
        f"Overall Risk Level: {safe(scores.get('overall_label'))} "
        f"({safe(scores.get('overall_risk'))}/100). "
        "This assessment combines metadata integrity, tampering analysis, "
        "AI-based detection, and forensic consistency checks.",
        y,
    )
    y = divider(c, y)

    # -------- 2 --------
    overview = analysis.get("image_overview", {})
    y = header(c, "2. Image Overview", y)
    y = text(c, f"Resolution: {safe(overview.get('resolution'))}", y)
    y = text(c, f"File Size: {safe(overview.get('file_size'))}", y)
    y = text(c, f"Color Space: {safe(overview.get('color_space'))}", y)
    y = text(c, f"SHA-256 Hash: {safe(overview.get('sha256'))}", y)
    y = divider(c, y)

    # -------- 3 --------
    exif = analysis.get("exif_summary", {})
    y = header(c, "3. Metadata Analysis", y)
    y = text(c, f"Device Make: {safe(exif.get('device_make'))}", y)
    y = text(c, f"Device Model: {safe(exif.get('device_model'))}", y)
    y = text(c, f"Timestamp: {safe(exif.get('datetime'))}", y)
    y = text(c, f"Software Tag: {safe(exif.get('software'))}", y)
    y = text(c, f"GPS Data Present: {exif.get('gps_present', False)}", y)
    y = divider(c, y)

    # -------- 4 --------
    ai = analysis.get("ai_detection", {})
    y = header(c, "4. AI / Synthetic Content Detection", y)
    y = text(c, f"Detection Enabled: {safe(ai.get('enabled'))}", y)
    y = text(c, f"AI Likelihood Score: {safe(ai.get('ai_generated_likelihood'))}/100", y)
    y = text(c, f"Classification: {safe(ai.get('label'))}", y)
    y = divider(c, y)

    # -------- 5 --------
    drivers = analysis.get("risk_drivers", [])
    y = header(c, "5. Risk Drivers & Evidence", y)
    y = bullet_list(c, drivers, y)
    y = divider(c, y)

    # -------- 6 --------
    y = header(c, "6. Tampering & Manipulation Analysis", y)
    tamper = analysis.get("tampering", {})
    y = text(c, f"ELA Score: {safe(tamper.get('ela_score'))}", y)
    y = text(c, f"Tampering Probability: {safe(tamper.get('probability'))}%", y)
    y = divider(c, y)

    # -------- 7 --------
    y = header(c, "7. Duplicate & Reuse Image Check", y)
    y = text(
        c,
        "No exact or near-duplicate matches found in local reference sets. "
        "Web-scale reverse image search not enabled in this build.",
        y,
    )
    y = divider(c, y)

    # -------- 8 --------
    y = header(c, "8. Geo & Timestamp Verification", y)
    y = text(
        c,
        "Geo-verification based on EXIF GPS data and visual cues. "
        "Confidence may be reduced if metadata is missing or inconsistent.",
        y,
    )
    y = divider(c, y)

    # -------- 9 --------
    y = header(c, "9. Risk Classification", y)
    y = text(c, f"Metadata Integrity Score: {safe(scores.get('metadata_score'))}", y)
    y = text(c, f"Tampering Score: {safe(scores.get('tampering_score'))}", y)
    y = text(c, f"AI Risk Score: {safe(scores.get('ai_score'))}", y)
    y = text(c, f"Overall Risk Rating: {safe(scores.get('overall_label'))}", y)
    y = divider(c, y)

    # -------- 10 --------
    y = header(c, "10. Visual Risk Legend", y)
    y = text(c, "Blue: Highly Authentic", y)
    y = text(c, "Green: Low Risk", y)
    y = text(c, "Amber: Medium Risk", y)
    y = text(c, "Red: High Fraud Risk", y)
    y = divider(c, y)

    # -------- 11 --------
    y = header(c, "11. PinIT Recommendation to Insurance Team", y)
    y = text(
        c,
        analysis.get(
            "recommendation",
            "Manual review recommended. Request original capture and supporting evidence."
        ),
        y,
    )
    y = divider(c, y)

    # -------- 12 --------
    y = header(c, "12. Legal & Compliance Disclaimer", y)
    y = text(
        c,
        "This report is generated using automated forensic analysis and AI-based heuristics. "
        "Results are probability-based and must be reviewed by qualified personnel. "
        "PinIT does not make final claim approval or rejection decisions.",
        y,
    )

    c.showPage()
    c.save()
